<br/><h2><a name="07172012">17 Jun 2012</a></h2> <p>MLP Collectors, make sure you visit the 2012 MLP Fair in Florida this year! Tickets are still available. Check out show details at : <a href="http://www.mylittleponycon.com/">http://www.mylittleponycon.com/</a><br/>
We always love this show!</p>
<br/><h2><a name="02142012">14 Feb 2012</a></h2> <p>KLECT loves our users and announces the expansion of free services in the site! Now users can apply custom photos to their collection and now all users can post items for sale or buy items in the Marketplace. Other features such as the condition of an item being displayed on the image, wishlists and alerts all continue to be provided to users securely and for no charge!</p>
<br/><h2><a name="07252011">25 July 2011</a></h2> <p>KLECT included in the 100th Anniversary Show for My Little Pony Talk!  Congratulations from KLECT on reaching 100 shows, it is our pleasure to participate and contribute. Click <a href="http://www.blogtalkradio.com/my-little-pony-talk/2011/07/23/100th-episode--7222011">here</a> to check out their show!</p>
<br/><h2><a name="07072011">7-8 July 2011</a></h2> <p>KLECT will be again participating at this year's MLP Fair. The 2011 MLP Fair is being held at Hasbro's Headquarters in Rhode Island. KLECT will again have a booth and presentation, including the announcement of new features and the update of G2 Data! More information is at <a href="http://mlpfair.eventbrite.com/" target="_blank">My Little Pony Fair and Convention 2011</a></p>		
<br/><br/>
<br/><h2><a name="07042011">7 Apr 2011</a></h2> <p>KLECT will be debuting at the American Stamp Dealers Association in New York City, April 7-10th. Show details are <a href="http://www.americanstampdealer.com/asdanews.htm" target="_blank">here</a>.</p>
<br/><br/>
<h2><a name="29032011">29 Mar 2011</a></h2> <p>US Stamps Official Launch<br/><br/>
Austin, Texas - What is typically 22 cm by 18.5 cm, decorative, commemorative and can be a snapshot of United States History? A stamp. 35% of the World's population can immediately connect Scott Number C3a with the image of what is considered by some to be the most prized error in philately, the Inverted Jenny. There are libraries, catalogues, software packages and volumes of books dedicated to the more than 400,000 types of stamps. However, there are no comprehensive, mobile systems that allow collectors to enjoy their hobby on the run while also alleviating the stressors associated with selling, buying and tracking their collection.
<br/><br/>
Austin start-up, KLECT Corp., has begun bridging this gap with the debut of their Airmail catalogue. Their next addition, US Postage stamps, will be debuted at the American Stamp Dealers Association's stamp show in New York City on April 7, 2011. KLECT will provide collectors with a comprehensive place to manage their collections, and enable them to buy and sell in a secure environment. Only the selling function of the web site requires a subscription. Otherwise, KLECT's membership and services are free!
<br/><br/>
<a href="<?=base_url()?>static/March292011.doc">Download Official Press Release Here</a>
<br/><br/>
<h2><a name="01032011">1 Mar 2011</a></h2> <p>Introducing US AIRMAIL on KLECT!<br/><br/>
Can't keep track of how many stamps you have or what stamps you are missing? Let KLECT.com help! KLECT now brings you the US AirMail stamp catalogue. You will be able to inventory, value, buy or sell your stamps whether you are at home surrounded by your collection or mobile. In addition to the  Scott Number and basic description  and image of each stamp, keep track of the stamps you have, quantity and individually customize the details. We hope you enjoy the site and be on the look out for our next stamp expansion! If you have any questions or suggestions, please send an e-mail us at contact@klect.com.</p>
<br/>
<h2><a name="01022011">1 Feb 2011</a></h2> <p>Austin, Texas - With a steady increase in activity surrounding the successful launched of the Marketplace, fresh to market KLECT Corp. has quickly added a new addition. The company's newest development - an intern from the University of Texas at Austin, Senior Communication Studies major and business certificate candidate, Elizabeth Bula.
<br/><br/>
Bula will be spearheading KLECT's communication efforts while assisting in software design support and operations. When asked why KLECT, she responded with a ode to the passion behind the business, "KLECT is more than a business venture. The passion that drives the ideas behind the company is unmatched. It is truly about the collectors, the passion for their collections and connecting community members from all over the world. Plus, I KLECT!"</p>
<br/>		
<h2><a name="06082010">6 Aug 2010</a></h2> <p>KLECT recieves its first press coverage in the Austin Business Journal. You can read the article <a href="http://austin.bizjournals.com/austin/stories/2010/08/09/smallb1.html?b=1281326400^3761301" target="_blank">here</a>.</p>
<br/>	
<h2><a name="03082010">3 Aug 2010</a></h2> <p>KLECT launches our first contest for My Little Pony users. A series of weekly 'hints' posted to allow users to find and identify a secret icon for a drawing. The contest runs through the end of the month of August and will select 2 winners from the users that have entered the contest. Winners will either win the 2010 MLP Hasbro LE Show or the G2 Collectors book, written by Summer Hayes.</p>
<br/>
<h2><a name="17072010">17 July 2010</a></h2> <p>KLECT debuts at the 2010 National MLP conference, July 17th and 18th  in Lexington, KY. KLECT has been invited to make a presentation to the over 200 MLP collectors, demonstrating how KLECT's inventory management system can enable them to inventory, manage and value their collections. As an exhibitor, KLECT will also provide live demonstrations and assistance for users in setting up their accounts from either computers or smart phones. <a href="http://purplepajamapress.com/home">http://purplepajamapress.com/home</a></p>
<br/>
<h2><a name="15072010">15 July 2010</a></h2> <p>KLECT Launch Party.  KLECT hosted an event at Cool River in Austin, Texas, to celebrate the launch of its new website—an innovative online community and management system for collectors.  President Ryan Zintgraff presented an overview of the website's current features and a description of soon-to-be-added advances, followed by a live demonstration of KLECT's inventory management tools by Ryan Hollister.</p>