<h2>17 Jun 2012</h2><p>MLP Collectors, make sure you visit the 2012 MLP Fair in Florida this year! Tickets are still available. Check out show details at : <a href="http://www.mylittleponycon.com/">http://www.mylittleponycon.com/</a><br/>
We always love this show!</p>
<h2>14 Feb 2012</h2><p>KLECT loves our users and announces the expansion of free services in the site! Now users can apply custom photos to their collection and now all users can post items for sale or buy items in the Marketplace. Other features such as the condition of an item being displayed on the image, wishlists and alerts all continue to be provided to users securely and for no charge!</p>
<h2>25 Jul 2011</h2><p>KLECT included in the 100th Anniversary Show for My Little Pony Talk!  Congratulations from KLECT on reaching 100 shows, it is our pleasure to participate and contribute. Click <a href="http://www.blogtalkradio.com/my-little-pony-talk/2011/07/23/100th-episode--7222011">here</a> to check out their show!<a style="float:right" href="<?=base_url()?>site/news/#07252011">Read more...</a><br/></p> 

<h2>7-8 July 2011</h2> <p>KLECT will be again participating at this year's MLP Fair. The 2011 MLP Fair is being held at Hasbro's Headquarters in Rhode Island. <br/><a style="float:right" href="<?=base_url()?>site/news/#07072011">Read more...</a><br/></p>
		
<h2>7 Apr 2011</h2> <p>KLECT will be debuting at the American Stamp Dealers Association in New York City, April 7-10th. Show details are <a href="http://www.americanstampdealer.com/asdanews.htm" target="_blank">here</a>.<br/><a style="float:right" href="<?=base_url()?>site/news/#07042011">Read more...</a><br/></p>
			
<h2>29 Mar 2011</h2> <p>Austin start-up, KLECT Corp., has begun bridging this gap with the debut of their Airmail catalogue. Their next addition, US Postage stamps, will be debuted at the American Stamp Dealers Association's stamp show in New York City on April 7, 2011. KLECT will provide collectors with a comprehensive place to manage their collections, and enable them to buy and sell in a secure environment.<br/><a style="float:right" href="<?=base_url()?>site/news/#29032011">Read more...</a><br/></p>
	