<h2>25 Jul 2011</h2><p>KLECT included in the 100th Anniversary Show for My Little Pony Talk!  Congratulations from KLECT on reaching 100 shows, it is our pleasure to participate and contribute. Click <a href="http://www.blogtalkradio.com/my-little-pony-talk/2011/07/23/100th-episode--7222011">here</a> to check out their show!<a style="float:right" href="<?=base_url()?>site/news/#07252011">Read more...</a><br/></p> 

<h2>7-8 July 2011</h2> <p>KLECT will be again participating at this year's MLP Fair. The 2011 MLP Fair is being held at Hasbro's Headquarters in Rhode Island. <br/><a style="float:right" href="<?=base_url()?>site/news/#07072011">Read more...</a><br/></p>
		
<h2>7 Apr 2011</h2> <p>KLECT will be debuting at the American Stamp Dealers Association in New York City, April 7-10th. Show details are <a href="http://www.americanstampdealer.com/asdanews.htm" target="_blank">here</a>.<br/><a style="float:right" href="<?=base_url()?>site/news/#07042011">Read more...</a><br/></p>
			
<h2>29 Mar 2011</h2> <p>Austin start-up, KLECT Corp., has begun bridging this gap with the debut of their Airmail catalogue. Their next addition, US Postage stamps, will be debuted at the American Stamp Dealers Association's stamp show in New York City on April 7, 2011. KLECT will provide collectors with a comprehensive place to manage their collections, and enable them to buy and sell in a secure environment.<br/><a style="float:right" href="<?=base_url()?>site/news/#29032011">Read more...</a><br/></p>

<h2>1 Mar 2011</h2> <p>Introducing US AIRMAIL on KLECT! Can't keep track of how many stamps you have or what stamps you are missing? Let KLECT.com help! KLECT now brings you the US AirMail stamp catalogue. You will be able to inventory, value, buy or sell your stamps whether you are at home surrounded by your collection or mobile. <br/><a style="float:right" href="<?=base_url()?>site/news/#01032011">Read more...</a><br/></p>		

<h2>1 Feb 2011</h2> <p>Austin, Texas - With a steady increase in activity surrounding the successful launched of the Marketplace, fresh to market KLECT Corp. has quickly added a new addition. The company's newest development - an intern from the University of Texas at Austin, Senior Communication Studies major and business certificate candidate, Elizabeth Bula. <br/><a style="float:right" href="<?=base_url()?>site/news/#01022011">Read more...</a><br/></p>